# Generated by Django 4.2.29 on 2026-03-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='payment_type',
            field=models.CharField(choices=[('HONORARIOS', 'Honorarios'), ('IMPUESTOS', 'Impuestos'), ('OTROS', 'Otros')], db_index=True, default='HONORARIOS', max_length=20),
        ),
    ]
