# Generated by Django 4.2.29 on 2026-03-10 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0005_backfill_submission_fiscal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0008_seed_py_fiscal_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('PROVISORIO', 'Provisorio'), ('FLUJO_CAJA', 'Flujo de caja'), ('OTRO', 'Otro')], db_index=True, default='PROVISORIO', max_length=20)),
                ('request_type_other', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitado'), ('IN_PROGRESS', 'En proceso'), ('COMPLETED', 'Realizado'), ('ARCHIVED', 'Archivado')], db_index=True, default='REQUESTED', max_length=20)),
                ('receipts_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('LOADED', 'Cargado')], db_index=True, default='PENDING', max_length=10)),
                ('invoices_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('LOADED', 'Cargado')], db_index=True, default='PENDING', max_length=10)),
                ('receipts_loaded_at', models.DateTimeField(blank=True, null=True)),
                ('invoices_loaded_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_requests_archived', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_requests', to='clients.client')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_requests_completed', to=settings.AUTH_USER_MODEL)),
                ('invoices_loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_requests_invoices_loaded', to=settings.AUTH_USER_MODEL)),
                ('invoices_pending_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_bank_requests', to='operations.pendingitem')),
                ('receipts_loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_requests_receipts_loaded', to=settings.AUTH_USER_MODEL)),
                ('receipts_pending_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_bank_requests', to='operations.pendingitem')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_bank_requests', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, limit_choices_to={'role': 'FUNCIONARIO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bank_requests', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_requests_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'responsible'], name='banks_bankr_status_f5c1cb_idx'), models.Index(fields=['client', 'status'], name='banks_bankr_client__e6e228_idx'), models.Index(fields=['receipts_status', 'invoices_status'], name='banks_bankr_receipt_768b5f_idx')],
            },
        ),
    ]
