# Generated by Django 4.2.29 on 2026-03-10 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrequest',
            name='last_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankrequest',
            name='last_note_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankrequest',
            name='last_note_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_requests_last_noted', to=settings.AUTH_USER_MODEL),
        ),
    ]
