# Generated by Django 4.2.29 on 2026-03-13 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0002_bankrequest_last_note_bankrequest_last_note_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrequest',
            name='receipts_client_notified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bankrequest',
            name='receipts_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankrequest',
            name='receipts_notified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_requests_receipts_notified', to=settings.AUTH_USER_MODEL),
        ),
    ]
