# Generated by Django 4.2.29 on 2026-03-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_bankrequest_receipts_client_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrequest',
            name='operational_reason',
            field=models.CharField(choices=[('MISSING_UPLOAD', 'Falta cargar recibos'), ('RECEIPTS_MISSING', 'Recibos en falta'), ('OTHER', 'Otro')], db_index=True, default='MISSING_UPLOAD', max_length=30),
        ),
        migrations.AddField(
            model_name='bankrequest',
            name='operational_reason_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankrequest',
            name='request_priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgente')], db_index=True, default='NORMAL', max_length=10),
        ),
    ]
