# Generated by Django 4.2.29 on 2026-03-09 19:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('ruc', models.CharField(blank=True, max_length=32)),
                ('ruc_base', models.CharField(blank=True, db_index=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('zone', models.CharField(choices=[('SANTA_RITA', 'Santa Rita'), ('KM_32', 'KM 32'), ('COMISIONES', 'Comisiones'), ('KATUETE', 'Katuete'), ('SUSPENDIDO', 'Suspendido'), ('OTHER', 'Otra')], db_index=True, default='SANTA_RITA', max_length=20)),
                ('presentation_type', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('pending_notes', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('monthly_amount_pyg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('monthly_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('paid', models.BooleanField(default=False)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('contract_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('SUSPENDED', 'Suspendido')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'), models.Index(fields=['ruc'], name='clients_cli_ruc_ca1515_idx'), models.Index(fields=['zone', 'status'], name='clients_cli_zone_03c156_idx'), models.Index(fields=['due_date'], name='clients_cli_due_dat_dfdb83_idx')],
            },
        ),
    ]
