# Generated by Django 4.2.29 on 2026-03-09 23:55

import unicodedata

from django.db import migrations, models
import django.db.models.deletion


DEFAULT_OBLIGATIONS = [
    {
        "code": "IVA_GENERAL",
        "name": "IVA General",
        "uses_ruc_calendar": True,
    },
    {
        "code": "IRE_GENERAL",
        "name": "IRE General",
        "uses_ruc_calendar": True,
    },
    {
        "code": "IRE_SIMPLE",
        "name": "IRE Simple",
        "uses_ruc_calendar": True,
    },
    {
        "code": "IRE_RESIMPLE",
        "name": "IRE Resimple",
        "uses_ruc_calendar": True,
    },
    {
        "code": "IRP_SERVICIOS_PERSONALES",
        "name": "IRP Servicios Personales",
        "uses_ruc_calendar": True,
    },
    {
        "code": "IRP_RENTAS_GANANCIAS_CAPITAL",
        "name": "IRP Rentas y Ganancias de Capital",
        "uses_ruc_calendar": True,
    },
    {
        "code": "REGISTRO_COMPROBANTES_MARANGATU",
        "name": "Registro Anual de Comprobantes (IRP-RSP / obligación 715)",
        "uses_ruc_calendar": False,
    },
]


def _normalize_text(value):
    text = value or ""
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    text = text.replace("-", " ").replace("_", " ").replace("/", " ")
    return " ".join(text.upper().split())


def _infer_obligation_codes(raw_value):
    normalized = _normalize_text(raw_value)
    if not normalized:
        return [], False

    codes = set()

    if "IVA" in normalized:
        codes.add("IVA_GENERAL")

    if (
        "IRE RESIMPLE" in normalized
        or "IRE RE SIMPLE" in normalized
        or "RESIMPLE" in normalized
        or "F502" in normalized
    ):
        codes.add("IRE_RESIMPLE")
    if "IRE SIMPLE" in normalized or "F501" in normalized:
        codes.add("IRE_SIMPLE")
    if "IRE GENERAL" in normalized:
        codes.add("IRE_GENERAL")

    if (
        "IRP SERVICIOS PERSONALES" in normalized
        or "IRP SERVICIO" in normalized
        or "SERVICIOS PERSONALES" in normalized
        or "F515" in normalized
    ):
        codes.add("IRP_SERVICIOS_PERSONALES")
    if (
        "IRP RENTAS Y GANANCIAS DE CAPITAL" in normalized
        or "IRP RENTA" in normalized
        or "GANANCIAS DE CAPITAL" in normalized
        or "F516" in normalized
    ):
        codes.add("IRP_RENTAS_GANANCIAS_CAPITAL")

    if (
        "MARANGATU" in normalized
        or "REGISTRO DE COMPROBANTES" in normalized
        or "REGISTRO ANUAL DE COMPROBANTES" in normalized
        or "IRP RSP" in normalized
        or "715" in normalized
    ):
        codes.add("REGISTRO_COMPROBANTES_MARANGATU")

    ambiguous = False
    ire_codes = {"IRE_GENERAL", "IRE_SIMPLE", "IRE_RESIMPLE"} & codes
    if "IRE" in normalized and not ire_codes:
        ambiguous = True
    if len(ire_codes) > 1:
        ambiguous = True

    irp_codes = {"IRP_SERVICIOS_PERSONALES", "IRP_RENTAS_GANANCIAS_CAPITAL"} & codes
    if "IRP" in normalized and not irp_codes:
        ambiguous = True

    if not codes:
        ambiguous = True

    return sorted(codes), ambiguous


def seed_obligations_and_backfill(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    Obligation = apps.get_model("clients", "Obligation")
    ClientObligation = apps.get_model("clients", "ClientObligation")

    obligation_by_code = {}
    for data in DEFAULT_OBLIGATIONS:
        obligation, _ = Obligation.objects.update_or_create(
            code=data["code"],
            defaults={
                "name": data["name"],
                "uses_ruc_calendar": data["uses_ruc_calendar"],
                "is_active": True,
                "default_periodicity": "MONTHLY",
                "default_due_mode": "AUTO",
            },
        )
        obligation_by_code[data["code"]] = obligation

    for client in Client.objects.all().iterator():
        presentation_type = (client.presentation_type or "").strip()
        if not presentation_type:
            continue

        codes, ambiguous = _infer_obligation_codes(presentation_type)
        if not codes:
            ClientObligation.objects.create(
                client_id=client.id,
                obligation_id=None,
                status="ACTIVE",
                periodicity="MONTHLY",
                due_mode="MANUAL",
                needs_manual_review=True,
                source_presentation_type=presentation_type[:255],
                observations="No se pudo mapear automáticamente desde presentation_type. Revisión manual requerida.",
            )
            continue

        for code in codes:
            obligation = obligation_by_code.get(code)
            if not obligation:
                continue
            defaults = {
                "status": "ACTIVE",
                "periodicity": "MONTHLY",
                "due_mode": "AUTO",
                "needs_manual_review": ambiguous,
                "source_presentation_type": presentation_type[:255],
            }
            ClientObligation.objects.update_or_create(
                client_id=client.id,
                obligation_id=obligation.id,
                defaults=defaults,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uses_ruc_calendar', models.BooleanField(default=False)),
                ('default_periodicity', models.CharField(blank=True, default='MONTHLY', max_length=20)),
                ('default_due_mode', models.CharField(blank=True, default='AUTO', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('INACTIVE', 'Inactiva')], db_index=True, default='ACTIVE', max_length=20)),
                ('periodicity', models.CharField(choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('ANNUAL', 'Anual'), ('OTHER', 'Otra')], default='MONTHLY', max_length=20)),
                ('due_mode', models.CharField(choices=[('AUTO', 'Automático por RUC'), ('MANUAL', 'Manual')], default='AUTO', max_length=20)),
                ('manual_due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('needs_manual_review', models.BooleanField(db_index=True, default=False)),
                ('source_presentation_type', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_obligations', to='clients.client')),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_obligations', to='clients.obligation')),
            ],
            options={
                'ordering': ['obligation__name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientobligation',
            constraint=models.UniqueConstraint(condition=models.Q(('obligation__isnull', False)), fields=('client', 'obligation'), name='unique_client_obligation_when_obligation_set'),
        ),
        migrations.RunPython(seed_obligations_and_backfill, migrations.RunPython.noop),
    ]
