# Generated by Django 4.2.29 on 2026-03-09 23:58

from django.db import migrations, models


def backfill_ruc_dv_from_ruc(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    for client in Client.objects.all().iterator():
        ruc = (client.ruc or "").strip()
        if not ruc or "-" not in ruc or client.ruc_dv:
            continue
        dv = "".join(ch for ch in ruc.split("-")[-1] if ch.isdigit())
        if dv:
            client.ruc_dv = dv[:4]
            client.save(update_fields=["ruc_dv", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_obligation_clientobligation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ruc_dv',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.RunPython(backfill_ruc_dv_from_ruc, migrations.RunPython.noop),
    ]
