# Generated by Django 4.2.29 on 2026-03-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_ruc_dv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zone',
            field=models.CharField(choices=[('SANTA_RITA', 'Santa Rita'), ('KM_32', 'KM 32'), ('COMISIONES', 'Misiones'), ('KATUETE', 'Katuete'), ('SUSPENDIDO', 'Suspendido'), ('OTHER', 'Otra')], db_index=True, default='SANTA_RITA', max_length=20),
        ),
    ]
