# Generated by Django 4.2.29 on 2026-03-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_responsible_clientresponsibilityhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='form_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='obligation',
            name='tax_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
