# Generated by Django 4.2.29 on 2026-03-10 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0008_seed_py_fiscal_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invoice_period_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RECEIVED', 'Recibidas')], db_index=True, default='PENDING', max_length=10, verbose_name='Facturas del período'),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_period_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_period_status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_invoice_period_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
