# Generated by Django 4.2.29 on 2026-03-10 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def backfill_current_month_invoice_status(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    ClientInvoicePeriodStatus = apps.get_model("clients", "ClientInvoicePeriodStatus")
    today = timezone.localdate()
    year = today.year
    month = today.month

    for client in Client.objects.all().iterator():
        has_legacy_signal = (
            client.invoice_period_status != "PENDING"
            or client.invoice_period_status_updated_at is not None
            or client.invoice_period_status_updated_by_id is not None
        )
        if not has_legacy_signal:
            continue

        status = client.invoice_period_status if client.invoice_period_status in {"PENDING", "RECEIVED"} else "PENDING"
        ClientInvoicePeriodStatus.objects.get_or_create(
            client_id=client.id,
            year=year,
            month=month,
            defaults={
                "status": status,
                "updated_by_id": client.invoice_period_status_updated_by_id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0009_client_invoice_period_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoicePeriodStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RECEIVED', 'Recibidas')], db_index=True, default='PENDING', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_period_records', to='clients.client')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_invoice_period_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'client_id'],
                'indexes': [models.Index(fields=['year', 'month', 'status'], name='clients_cli_year_d6fc5d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='clientinvoiceperiodstatus',
            constraint=models.UniqueConstraint(fields=('client', 'year', 'month'), name='unique_client_invoice_period_status'),
        ),
        migrations.RunPython(backfill_current_month_invoice_status, migrations.RunPython.noop),
    ]
