# Generated by Django 4.2.29 on 2026-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_clientinvoiceperiodstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinvoiceperiodstatus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('RECEIVED', 'Recibidas')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
