# Generated by Django 4.2.29 on 2026-03-09 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SUBMITTED', 'Presentado'), ('LATE', 'Atrasado')], db_index=True, default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('missing_documents', models.TextField(blank=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('URGENT', 'Urgente'), ('SOON', 'Próximo'), ('OK', 'Normal')], db_index=True, default='OK', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Activa'), ('RESOLVED', 'Resuelta')], db_index=True, default='OPEN', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_items', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pending_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'expected_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.DateField(db_index=True)),
                ('obligation_type', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('AUTO', 'Automático'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10)),
                ('priority', models.CharField(choices=[('URGENT', 'Urgente'), ('SOON', 'Próximo'), ('OK', 'Normal')], db_index=True, default='OK', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('COMPLETED', 'Completado')], db_index=True, default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deadlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'priority'],
            },
        ),
    ]
