# Generated by Django 4.2.29 on 2026-03-09 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_pending_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
