# Generated by Django 4.2.29 on 2026-03-10 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0002_pendingitem_deleted_at_pendingitem_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
