# Generated by Django 4.2.29 on 2026-03-10 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_obligation_fiscal_fields'),
        ('operations', '0003_submission_archived_at_submission_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='needs_manual_review',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='clients.obligation'),
        ),
        migrations.AddField(
            model_name='submission',
            name='period_kind',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual'), ('OTHER', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='period_month',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='period_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
