# Generated by Django 4.2.29 on 2026-03-11 14:54

from django.db import migrations, models


def map_soon_priority_to_ok(apps, schema_editor):
    PendingItem = apps.get_model("operations", "PendingItem")
    Deadline = apps.get_model("operations", "Deadline")
    PendingItem.objects.filter(priority="SOON").update(priority="OK")
    Deadline.objects.filter(priority="SOON").update(priority="OK")


def reverse_map_noop(apps, schema_editor):
    # No reversible mapping with full fidelity once SOON is consolidated into OK.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_backfill_submission_fiscal_fields'),
    ]

    operations = [
        migrations.RunPython(map_soon_priority_to_ok, reverse_map_noop),
        migrations.AlterField(
            model_name='deadline',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'Urgente'), ('OK', 'Normal')], db_index=True, default='OK', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingitem',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'Urgente'), ('OK', 'Normal')], db_index=True, default='OK', max_length=10),
        ),
    ]
