# Generated by Django 4.2.29 on 2026-03-11 17:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0012_update_obligation_catalog_2026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_type', models.CharField(choices=[('IRE', 'Pago de IRE'), ('IDU', 'Pago de IDU'), ('FACILIDAD', 'Pago de facilidad'), ('ANTICIPO', 'Anticipo'), ('MAQUILA_F107', 'Tributo Unico Maquila (F107)'), ('OTHER', 'Otro')], db_index=True, max_length=20)),
                ('type_other', models.CharField(blank=True, max_length=120)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('period_reference', models.CharField(blank=True, max_length=120)),
                ('installment_group_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('installment_number', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('installment_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(choices=[('PYG', 'Guarani'), ('USD', 'Dolar')], default='PYG', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('NOTIFIED', 'Avisado'), ('PAID', 'Pagado'), ('ARCHIVED', 'Archivado')], db_index=True, default='PENDING', max_length=12)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('ACCOUNT_STATEMENT_IMPORT', 'Importado desde estado de cuenta')], db_index=True, default='MANUAL', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_commitments', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_commitments_created', to=settings.AUTH_USER_MODEL)),
                ('notified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_commitments_notified', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_commitments_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'client__name', 'id'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='tax_commitm_status_457737_idx'), models.Index(fields=['client', 'status'], name='tax_commitm_client__bf3840_idx'), models.Index(fields=['commitment_type', 'due_date'], name='tax_commitm_commitm_5176cd_idx'), models.Index(fields=['source', 'status'], name='tax_commitm_source_c32212_idx')],
            },
        ),
    ]
