# Generated by Django 4.2.29 on 2026-03-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_commitments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcommitment',
            name='installment_mode',
            field=models.CharField(choices=[('AUTO', 'Automatico'), ('MANUAL', 'Manual')], db_index=True, default='AUTO', max_length=10),
        ),
    ]
