# Generated by Django 4.2.29 on 2026-03-13 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0012_update_obligation_catalog_2026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(db_index=True)),
                ('paid_by', models.CharField(max_length=120)),
                ('concept_type', models.CharField(choices=[('HONORARIOS', 'Honorarios'), ('IMPUESTOS', 'Impuestos'), ('ANTICIPOS', 'Anticipos'), ('FACILIDAD', 'Facilidad'), ('OTROS', 'Otros')], db_index=True, max_length=20)),
                ('concept_other', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo'), ('CHEQUE_PROPIO', 'Cheque propio'), ('CHEQUE_TERCERO', 'Cheque de tercero'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('third_party_check_name', models.CharField(blank=True, max_length=160)),
                ('observation', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs_archived', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reception_logs', to='clients.client')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['client', 'payment_date'], name='payment_log_client__a8c503_idx'), models.Index(fields=['concept_type', 'payment_method'], name='payment_log_concept_acb966_idx')],
            },
        ),
    ]
